version: '3.4'

services:
  employeemanagementsystem.webapi:
    image: ${DOCKER_REGISTRY-}employeemanagementsystemwebapi
    build:
      context: .
      dockerfile: src/EmployeeManagementSystem.WebApi/Dockerfile

  employeemanagementsystem.client:
    image: ${DOCKER_REGISTRY-}employeemanagementsystemclient
    build:
      context: .
      dockerfile: src/EmployeeManagementSystem.Client/Dockerfile

