version: '3.4'

services:
  employeemanagementsystem.webapi:
    container_name: web_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8083:80" 
    networks:
      - net_employeemanagementsystem

  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "og~8O+nwAT%5c0a8V8G]G+tEi"
    ports:
      - 1433:1433
    volumes:
      - sql-server-volume:/var/opt/mssql
    networks:
      - net_employeemanagementsystem  

  employeemanagementsystem.client:
    container_name: client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80" 
    networks:
      - net_employeemanagementsystem
networks:
  net_employeemanagementsystem:
    driver: bridge
    external: true
volumes:
  sql-server-volume:


